public class ApexBookExample {
    
    public static void BooksWithAuthors()
    {
        List<String> authors = new List<String>();
        authors.add('Peter Baker');
        authors.add('Lamar Odam');
        authors.add('Ashis Ray');
        
        List<String> books = new List<String>();
        books.add('Obama-The Call of History');
        books.add('Listening,Learning and Leading');
        books.add('Darkness of Light');
        
        for(String i : authors)
        {
            for(String j : books)
            {
                
            }
          }
        
    }
}