public class IfStatementEg1 {
    
    public static void decision()
    {
        // I have a confusion am i daring enough or not so i made im daring
        Boolean amIDaring =True;
        
        // if the condition is true then if statement is exicuted 
        if(amIDaring){
            System.debug('I can achieve this easily Im brave');
        }
        //if condition is false else statement is exicuted.
        else
        {
            System.debug('No Im not');
        }
    }

}