public class SetEg1 {
      public static void setMethod() 
      {
           //Set is the collection of multiple number of records unordered unique data and it cannot have unique values
    Set<String> records = new Set<String>{'Vanditha' ,'Chair', '1234','Vanditha'};
        
        //When you debug you can see the records been arranged 
    System.debug('Unordered records are' + records);
      }
      
}