public class simpleExample2
{  
    public static void simpleExample()
    {
        //List contains the weekdays
        
      List<String> Student = new List<String>();    
        
        for(integer score=50; score<100;score++)
        {
             if(score >= 70)
        {
            System.debug('Woww');
        }
        else if(score >= 80)
         {
            System.debug('You can reach');
         }
            else if(score >= 90)
           {
                System.debug('Almost Their');
           }
            else
            {
            system.debug('Your score is less than 60');
            }
        }
       
    }
}